name: CI Release

on:
  push:
    tags:
      - v*

jobs:
  builds:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Branch name
        id: branch_name
        run: |
          echo "VER=`./scripts/buildversion.sh`" >> $GITHUB_OUTPUT
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.6'
      - name: Test
        run: make test
      - name: Build
        run: |
          make cleanpackage && \
          make release
      - name: Release files
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.GIT_PASS }}
          file: packages/neoshell-v*.zip
          repo_name: machbase/neo-shell
          prerelease: true
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
